name: comcent
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.2
  cloud_firestore: ^0.14.2
  firebase_core: ^0.5.1
  firebase_storage: ^4.0.1
  intl: ^0.16.1
  provider: ^4.3.2+2
  cool_alert: ^1.0.1
  file_picker: ^2.1.4
  flushbar: ^1.10.4
  datetime_picker_formfield: ^1.0.0
  image_picker: ^0.6.7+12
  circular_profile_avatar: ^1.0.8
  validated: ^1.0.3
  video_thumbnail: ^0.2.4
  flutter_dropdown: ^0.0.8
  flutter_easyloading: ^2.1.2
  cached_network_image: ^2.5.0
  video_player: ^1.0.0
  chewie: ^0.12.0
  percent_indicator: ^2.1.8
  expandable: ^4.1.4
  uuid: ^2.2.2
  search_page: ^1.3.0
  speech_bubble: ^0.0.5
  timeago: ^2.0.29
  smooth_page_indicator: ^0.2.0
  readmore: ^1.0.0
  extended_image: ^1.5.0
  focused_menu: ^1.0.1
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.12+4
  after_layout: ^1.0.7+2
  dots_indicator: ^1.2.0
  flutter_email_sender: ^3.0.1
  advance_pdf_viewer: ^1.2.1+2
  bubble_tab_indicator: ^0.1.4
  flutter_staggered_grid_view: ^0.3.2
  animations: ^1.1.2
  sliding_up_panel: ^1.0.2
  flashy_tab_bar: ^0.0.3
  keyboard_dismisser: ^1.0.2
  grouped_list: ^3.7.1
  shimmer: ^1.1.2
  flutter_vector_icons: ^0.2.1
  url_launcher: ^5.7.10
  flutter_linkify: ^4.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/illustrations/